stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: busybox:1.27
          shellScript: |-
            echo ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
#  - name: Publish
#    steps:
#      - publishImageConfig:
#          dockerfilePath: ./Dockerfile
#          buildContext: .
#          tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
