kind: Service
apiVersion: v1
metadata:
  name: greenhouse-service
spec:
  selector:
    app: greenhouse
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-greenhouse
  labels:
    app: greenhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenhouse
  template:
    metadata:
      labels:
        app: greenhouse
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: maven
        image: nginx:1.19.0
        ports:
        - containerPort: 80
